// <auto-generated />
namespace EnergoImport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class eSubStatus2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eSubStatus2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810170628016_eSubStatus2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
